### ISSUE TITLE
OSError: libpcreposix.so.0

### ISSUE THREAD

**Issue by catroot** [antocuni/cppyy-backend#2]
While trying
'from cppyy.gbl import Concrete'
Got error:
'OSError: libcppyy_backend.so: cannot open shared object file: No such file or directory' followed by 
'OSError: libpcreposix.so.0: cannot open shared object file: No such file or directory'
cppyy installed from wheel

**Comment by yhtang** [comment]
Same issue here but with cppyy installed by pip.

**Comment by antocuni** [comment]
This is the wrong repo, it was just an experiment. Look here for the list of official cppyy repos:
https://cppyy.readthedocs.io/en/latest/repositories.html
